// 中国AI科创100指数成分股（模拟样本）+ 近期科创板新股 样本数据
// 说明：本项目为产品演示系统，行情/财务/评分数据均由模拟引擎生成，不构成任何投资建议。

export type PatternHint = "breakout" | "trend_up" | "range" | "volatile" | "trend_down";
export type GrowthTier = "high" | "mid" | "low";

export interface SeedStock {
  code: string;
  name: string;
  market: "科创板" | "创业板" | "沪主板" | "深主板";
  sector: string;
  concept: string;
  listedDaysAgo: number; // 上市至今天数（近似）
  isIndexMember: boolean;
  isNewIpo: boolean;
  basePrice: number;
  marketCapYi: number;
  pe: number;
  volatility: number; // 日波动幅度基准
  pattern: PatternHint;
  growthTier: GrowthTier;
  description: string;
}

const Y = 365;

export const SEED_STOCKS: SeedStock[] = [
  // ================= 中国AI科创100指数成分股（代表样本） =================
  { code: "688981", name: "中芯国际", market: "科创板", sector: "半导体制造", concept: "国产替代,晶圆代工,先进制程", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 58.2, marketCapYi: 4600, pe: 62, volatility: 0.022, pattern: "breakout", growthTier: "high", description: "中国大陆规模最大、技术最先进的集成电路晶圆代工企业，先进制程持续突破。" },
  { code: "688256", name: "寒武纪", market: "科创板", sector: "AI芯片", concept: "AI芯片,大模型算力,国产GPU", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 620, marketCapYi: 2600, pe: 0, volatility: 0.038, pattern: "breakout", growthTier: "high", description: "国内AI云端训练与推理芯片龙头，受益于大模型算力国产化浪潮。" },
  { code: "688008", name: "澜起科技", market: "科创板", sector: "芯片互连", concept: "内存接口芯片,AI服务器,DDR5", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 78.5, marketCapYi: 900, pe: 45, volatility: 0.024, pattern: "trend_up", growthTier: "high", description: "全球领先的内存接口芯片供应商，深度受益AI服务器DDR5升级周期。" },
  { code: "688041", name: "海光信息", market: "科创板", sector: "通用芯片", concept: "国产CPU,DCU,信创", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 96.3, marketCapYi: 2200, pe: 130, volatility: 0.027, pattern: "breakout", growthTier: "high", description: "国产x86兼容CPU与DCU协处理器领军企业，信创与AI算力双轮驱动。" },
  { code: "688169", name: "石头科技", market: "科创板", sector: "智能机器人", concept: "扫地机器人,AI算法,出海", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 265, marketCapYi: 350, pe: 18, volatility: 0.021, pattern: "range", growthTier: "mid", description: "全球领先的智能清洁机器人厂商，AI视觉导航与出海业务持续放量。" },
  { code: "688036", name: "传音控股", market: "科创板", sector: "智能终端", concept: "新兴市场手机,AI影像", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 88.4, marketCapYi: 1050, pe: 16, volatility: 0.02, pattern: "trend_up", growthTier: "mid", description: "深耕非洲及新兴市场的智能终端龙头，AI影像与本地化生态构筑壁垒。" },
  { code: "688111", name: "金山办公", market: "科创板", sector: "AI+软件", concept: "WPS,办公软件,大模型应用", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 268, marketCapYi: 1300, pe: 68, volatility: 0.023, pattern: "trend_up", growthTier: "high", description: "国产办公软件龙头，WPS AI持续商业化，订阅制收入稳健增长。" },
  { code: "688083", name: "中望软件", market: "科创板", sector: "工业软件", concept: "CAD/CAE,国产替代", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 95.6, marketCapYi: 130, pe: 0, volatility: 0.03, pattern: "breakout", growthTier: "high", description: "国产工业软件CAD/CAE领军者，受益于工业软件国产替代加速。" },
  { code: "688019", name: "安集科技", market: "科创板", sector: "半导体材料", concept: "抛光液,国产替代", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 158, marketCapYi: 175, pe: 55, volatility: 0.025, pattern: "trend_up", growthTier: "high", description: "国内领先的集成电路抛光液供应商，持续导入先进制程产线。" },
  { code: "688126", name: "沪硅产业", market: "科创板", sector: "半导体材料", concept: "硅片,国产替代", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 22.4, marketCapYi: 480, pe: 0, volatility: 0.026, pattern: "range", growthTier: "mid", description: "国内大硅片龙头企业，12英寸硅片持续放量。" },
  { code: "688012", name: "中微公司", market: "科创板", sector: "半导体设备", concept: "刻蚀机,国产替代", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 185, marketCapYi: 1150, pe: 58, volatility: 0.026, pattern: "breakout", growthTier: "high", description: "国产刻蚀设备龙头，先进制程验证进展顺利，订单饱满。" },
  { code: "688120", name: "华海清科", market: "科创板", sector: "半导体设备", concept: "CMP设备,国产替代", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 210, marketCapYi: 330, pe: 42, volatility: 0.029, pattern: "breakout", growthTier: "high", description: "国内化学机械抛光（CMP）设备龙头，持续拓展半导体设备品类。" },
  { code: "688003", name: "天准科技", market: "科创板", sector: "机器视觉", concept: "工业视觉,AI质检", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.1, marketCapYi: 62, pe: 0, volatility: 0.032, pattern: "volatile", growthTier: "mid", description: "工业机器视觉与智能检测装备供应商，AI质检需求持续释放。" },
  { code: "688322", name: "奥比中光", market: "科创板", sector: "AI视觉", concept: "3D视觉,机器人感知", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 46.8, marketCapYi: 90, pe: 0, volatility: 0.035, pattern: "breakout", growthTier: "high", description: "国内3D视觉感知龙头，机器人与AIoT感知模组需求快速增长。" },
  { code: "688207", name: "格灵深瞳", market: "科创板", sector: "AI视觉", concept: "计算机视觉,大模型应用", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 28.6, marketCapYi: 55, pe: 0, volatility: 0.04, pattern: "volatile", growthTier: "mid", description: "计算机视觉算法企业，聚焦城市管理与商业AI场景落地。" },
  { code: "688327", name: "云从科技", market: "科创板", sector: "AI平台", concept: "人机协同,大模型,AI四小龙", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 24.3, marketCapYi: 100, pe: 0, volatility: 0.037, pattern: "breakout", growthTier: "high", description: "人机协同AI平台厂商，聚焦行业大模型与信创场景落地。" },
  { code: "688088", name: "虹软科技", market: "科创板", sector: "AI视觉算法", concept: "手机影像算法,智能驾驶", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 32.5, marketCapYi: 130, pe: 40, volatility: 0.025, pattern: "trend_up", growthTier: "mid", description: "全球领先的视觉AI算法供应商，智能汽车业务成为新增长极。" },
  { code: "688072", name: "拓荆科技", market: "科创板", sector: "半导体设备", concept: "薄膜沉积设备,国产替代", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 168, marketCapYi: 380, pe: 48, volatility: 0.028, pattern: "trend_up", growthTier: "high", description: "国产薄膜沉积设备龙头，PECVD/ALD设备持续放量。" },
  { code: "688521", name: "芯原股份", market: "科创板", sector: "芯片IP", concept: "IP授权,芯片定制", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 62.4, marketCapYi: 240, pe: 0, volatility: 0.03, pattern: "range", growthTier: "mid", description: "国内领先的半导体IP授权与芯片定制服务提供商。" },
  { code: "688099", name: "晶晨股份", market: "科创板", sector: "多媒体芯片", concept: "AIoT芯片,智能终端", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 78.9, marketCapYi: 320, pe: 36, volatility: 0.023, pattern: "trend_up", growthTier: "mid", description: "全球领先的多媒体智能终端SoC芯片设计企业。" },
  { code: "688608", name: "恒玄科技", market: "科创板", sector: "智能穿戴芯片", concept: "TWS耳机芯片,AI耳机", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 205, marketCapYi: 260, pe: 62, volatility: 0.03, pattern: "breakout", growthTier: "high", description: "智能穿戴与AIoT芯片龙头，AI耳机新品类打开成长空间。" },
  { code: "688018", name: "乐鑫科技", market: "科创板", sector: "物联网芯片", concept: "AIoT,WiFi芯片", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 118, marketCapYi: 145, pe: 33, volatility: 0.026, pattern: "trend_up", growthTier: "mid", description: "全球领先的AIoT无线通信芯片方案商。" },
  { code: "688206", name: "概伦电子", market: "科创板", sector: "EDA", concept: "EDA软件,国产替代", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 22.1, marketCapYi: 95, pe: 0, volatility: 0.034, pattern: "breakout", growthTier: "high", description: "国产EDA稀缺标的，聚焦器件建模与晶圆制造类EDA工具。" },
  { code: "301269", name: "华大九天", market: "创业板", sector: "EDA", concept: "EDA软件,国产替代", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 135, marketCapYi: 620, pe: 150, volatility: 0.033, pattern: "breakout", growthTier: "high", description: "国内规模最大的EDA工具厂商，模拟电路EDA国内领先。" },
  { code: "301095", name: "广立微", market: "创业板", sector: "EDA/测试", concept: "良率提升,EDA", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 88.5, marketCapYi: 110, pe: 0, volatility: 0.036, pattern: "trend_up", growthTier: "high", description: "半导体成品率提升整体解决方案提供商，EDA软件加速放量。" },
  { code: "688507", name: "索辰科技", market: "科创板", sector: "工业软件", concept: "CAE仿真,国产替代", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 68.2, marketCapYi: 45, pe: 0, volatility: 0.04, pattern: "volatile", growthTier: "mid", description: "国产CAE仿真软件领军企业，航空航天等高端制造持续渗透。" },
  { code: "688279", name: "峰岹科技", market: "科创板", sector: "电机驱动芯片", concept: "机器人电机,BLDC芯片", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 152, marketCapYi: 90, pe: 55, volatility: 0.032, pattern: "trend_up", growthTier: "mid", description: "电机驱动控制芯片龙头，人形机器人关节电控需求打开空间。" },
  { code: "688052", name: "纳芯微", market: "科创板", sector: "传感器芯片", concept: "汽车电子,模拟芯片", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 148, marketCapYi: 240, pe: 0, volatility: 0.035, pattern: "breakout", growthTier: "high", description: "国内领先的信号感知与处理芯片供应商，车规产品放量。" },
  { code: "688213", name: "思特威", market: "科创板", sector: "CIS芯片", concept: "图像传感器,机器视觉", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 82.4, marketCapYi: 260, pe: 70, volatility: 0.033, pattern: "breakout", growthTier: "high", description: "CMOS图像传感器芯片设计公司，机器视觉与车载CIS快速增长。" },
  { code: "688337", name: "普源精电", market: "科创板", sector: "电子测量仪器", concept: "国产替代,高端仪器", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.6, marketCapYi: 55, pe: 0, volatility: 0.03, pattern: "range", growthTier: "mid", description: "国产电子测量仪器龙头，示波器等高端仪器持续国产替代。" },
  { code: "688158", name: "优刻得", market: "科创板", sector: "云计算", concept: "AI云,算力租赁", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 20.6, marketCapYi: 85, pe: 0, volatility: 0.038, pattern: "breakout", growthTier: "high", description: "独立云计算服务商，AI算力租赁业务成为新的收入引擎。" },
  { code: "688787", name: "海天瑞声", market: "科创板", sector: "AI数据服务", concept: "大模型语料,数据标注", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 118, marketCapYi: 45, pe: 0, volatility: 0.042, pattern: "breakout", growthTier: "high", description: "国内领先的AI训练数据服务商，大模型语料需求快速增长。" },
  { code: "688343", name: "云天励飞", market: "科创板", sector: "AI芯片", concept: "视觉芯片,城市大脑", listedDaysAgo: 1 * Y, isIndexMember: true, isNewIpo: true, basePrice: 36.2, marketCapYi: 95, pe: 0, volatility: 0.045, pattern: "breakout", growthTier: "high", description: "AI芯片与算法一体化企业，城市级AI应用规模化落地。" },
  { code: "300418", name: "昆仑万维", market: "创业板", sector: "大模型", concept: "AIGC,大模型,出海", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 46.8, marketCapYi: 420, pe: 0, volatility: 0.04, pattern: "breakout", growthTier: "high", description: "布局AIGC全栈能力的科技集团，海外AI应用矩阵持续扩张。" },
  { code: "002230", name: "科大讯飞", market: "深主板", sector: "AI平台", concept: "语音AI,大模型,教育AI", listedDaysAgo: 15 * Y, isIndexMember: true, isNewIpo: false, basePrice: 58.4, marketCapYi: 1350, pe: 0, volatility: 0.033, pattern: "trend_up", growthTier: "high", description: "国内智能语音与大模型领军企业，讯飞星火持续迭代。" },
  { code: "688777", name: "中控技术", market: "科创板", sector: "工业自动化", concept: "工业AI,智能制造", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.5, marketCapYi: 320, pe: 24, volatility: 0.024, pattern: "trend_up", growthTier: "mid", description: "国产流程工业自动化控制系统龙头，工业AI持续渗透。" },
  { code: "300229", name: "拓尔思", market: "创业板", sector: "AI+大数据", concept: "大模型,内容安全", listedDaysAgo: 12 * Y, isIndexMember: true, isNewIpo: false, basePrice: 16.8, marketCapYi: 70, pe: 0, volatility: 0.038, pattern: "volatile", growthTier: "mid", description: "大数据与人工智能技术企业，聚焦媒体与政务大模型应用。" },
  { code: "002362", name: "汉王科技", market: "深主板", sector: "AI识别", concept: "文字识别,人脸识别", listedDaysAgo: 14 * Y, isIndexMember: true, isNewIpo: false, basePrice: 24.6, marketCapYi: 60, pe: 0, volatility: 0.04, pattern: "breakout", growthTier: "mid", description: "手写识别与人工智能技术企业，AI笔纸交互产品持续创新。" },
  { code: "002253", name: "川大智胜", market: "深主板", sector: "AI识别", concept: "人脸识别,空管系统", listedDaysAgo: 16 * Y, isIndexMember: true, isNewIpo: false, basePrice: 28.4, marketCapYi: 65, pe: 0, volatility: 0.045, pattern: "volatile", growthTier: "low", description: "空管系统与人脸识别技术企业，三维人脸重建技术领先。" },
  { code: "002212", name: "天融信", market: "深主板", sector: "网络安全", concept: "AI安全,信创", listedDaysAgo: 17 * Y, isIndexMember: true, isNewIpo: false, basePrice: 12.4, marketCapYi: 100, pe: 0, volatility: 0.03, pattern: "range", growthTier: "low", description: "国内网络安全领军企业，布局AI驱动的主动防御体系。" },
  { code: "300454", name: "深信服", market: "创业板", sector: "网络安全", concept: "AI安全,云计算", listedDaysAgo: 8 * Y, isIndexMember: true, isNewIpo: false, basePrice: 88.6, marketCapYi: 190, pe: 0, volatility: 0.028, pattern: "trend_up", growthTier: "mid", description: "网络安全与云计算解决方案提供商，安全大模型持续落地。" },
  { code: "688031", name: "星环科技", market: "科创板", sector: "大数据平台", concept: "大数据,国产数据库", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 45.2, marketCapYi: 55, pe: 0, volatility: 0.04, pattern: "breakout", growthTier: "high", description: "国产大数据基础软件领军企业，大模型数据底座需求提升。" },
  { code: "688023", name: "安恒信息", market: "科创板", sector: "网络安全", concept: "AI安全,国产替代", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 62.4, marketCapYi: 105, pe: 0, volatility: 0.032, pattern: "volatile", growthTier: "mid", description: "国内网络安全综合服务商，安全智能化产品矩阵完善。" },
  { code: "688030", name: "山石网科", market: "科创板", sector: "网络安全", concept: "AI防火墙,信创", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 26.8, marketCapYi: 55, pe: 0, volatility: 0.036, pattern: "range", growthTier: "low", description: "下一代网络安全产品与解决方案提供商。" },
  { code: "300098", name: "高新兴", market: "创业板", sector: "AI物联网", concept: "车联网,视频AI", listedDaysAgo: 15 * Y, isIndexMember: true, isNewIpo: false, basePrice: 6.8, marketCapYi: 75, pe: 0, volatility: 0.045, pattern: "volatile", growthTier: "low", description: "智能物联网整体解决方案提供商，聚焦车联网与视频AI。" },
  { code: "688047", name: "龙芯中科", market: "科创板", sector: "国产CPU", concept: "信创,自主可控", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 58.6, marketCapYi: 240, pe: 0, volatility: 0.038, pattern: "trend_up", growthTier: "mid", description: "国产自主指令集CPU领军企业，信创市场持续渗透。" },
  { code: "688002", name: "睿创微纳", market: "科创板", sector: "红外芯片", concept: "红外热成像,车载感知", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 34.2, marketCapYi: 140, pe: 45, volatility: 0.03, pattern: "trend_up", growthTier: "mid", description: "国内红外热成像芯片龙头，车载与消费应用持续拓展。" },
  { code: "688385", name: "复旦微电", market: "科创板", sector: "芯片设计", concept: "FPGA,国产替代", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 32.4, marketCapYi: 260, pe: 0, volatility: 0.033, pattern: "breakout", growthTier: "high", description: "国产FPGA与智能电表芯片龙头企业，可编程逻辑器件持续突破。" },
  { code: "688123", name: "聚辰股份", market: "科创板", sector: "存储芯片", concept: "EEPROM,车规存储", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 78.4, marketCapYi: 100, pe: 32, volatility: 0.028, pattern: "trend_up", growthTier: "mid", description: "全球领先的存储芯片设计企业，车规级存储芯片持续放量。" },
  { code: "300613", name: "富瀚微", market: "创业板", sector: "视频监控芯片", concept: "AI视频SoC", listedDaysAgo: 6 * Y, isIndexMember: true, isNewIpo: false, basePrice: 68.4, marketCapYi: 85, pe: 0, volatility: 0.036, pattern: "breakout", growthTier: "high", description: "安防视频监控SoC芯片龙头，AI ISP芯片持续迭代。" },
  { code: "300458", name: "全志科技", market: "创业板", sector: "智能硬件SoC", concept: "AIoT,平板方案", listedDaysAgo: 9 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.6, marketCapYi: 130, pe: 40, volatility: 0.032, pattern: "trend_up", growthTier: "mid", description: "智能硬件应用处理器SoC设计企业，AIoT终端方案丰富。" },
  { code: "603893", name: "瑞芯微", market: "沪主板", sector: "边缘AI芯片", concept: "端侧大模型,AIoT", listedDaysAgo: 5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 128, marketCapYi: 620, pe: 95, volatility: 0.034, pattern: "breakout", growthTier: "high", description: "端侧AI芯片领军企业，端侧大模型部署需求快速释放。" },
  { code: "603986", name: "兆易创新", market: "沪主板", sector: "存储芯片", concept: "NOR Flash,MCU", listedDaysAgo: 8 * Y, isIndexMember: true, isNewIpo: false, basePrice: 98.6, marketCapYi: 660, pe: 55, volatility: 0.028, pattern: "trend_up", growthTier: "mid", description: "国内领先的存储芯片与MCU设计企业。" },
  { code: "603690", name: "至纯科技", market: "沪主板", sector: "半导体设备", concept: "清洗设备,国产替代", listedDaysAgo: 7 * Y, isIndexMember: true, isNewIpo: false, basePrice: 22.4, marketCapYi: 105, pe: 0, volatility: 0.036, pattern: "volatile", growthTier: "mid", description: "半导体湿法清洗设备国产化领军企业。" },
  { code: "605111", name: "新洁能", market: "沪主板", sector: "功率半导体", concept: "IGBT,国产替代", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 45.2, marketCapYi: 130, pe: 38, volatility: 0.03, pattern: "trend_up", growthTier: "mid", description: "国内功率半导体器件设计龙头企业。" },
  { code: "601138", name: "工业富联", market: "沪主板", sector: "AI服务器", concept: "算力硬件,AI服务器代工", listedDaysAgo: 6 * Y, isIndexMember: true, isNewIpo: false, basePrice: 26.8, marketCapYi: 5200, pe: 22, volatility: 0.026, pattern: "breakout", growthTier: "high", description: "全球领先的AI服务器与云计算基础设施制造商。" },
  { code: "300308", name: "中际旭创", market: "创业板", sector: "光模块", concept: "AI算力,800G光模块", listedDaysAgo: 12 * Y, isIndexMember: true, isNewIpo: false, basePrice: 138, marketCapYi: 1350, pe: 30, volatility: 0.035, pattern: "breakout", growthTier: "high", description: "全球领先的高速光模块供应商，AI算力网络核心受益标的。" },
  { code: "300502", name: "新易盛", market: "创业板", sector: "光模块", concept: "AI算力,光通信", listedDaysAgo: 10 * Y, isIndexMember: true, isNewIpo: false, basePrice: 105, marketCapYi: 700, pe: 35, volatility: 0.038, pattern: "breakout", growthTier: "high", description: "高速光模块领先厂商，受益于AI算力网络高景气。" },
  { code: "300394", name: "天孚通信", market: "创业板", sector: "光通信器件", concept: "AI算力,光器件", listedDaysAgo: 10 * Y, isIndexMember: true, isNewIpo: false, basePrice: 96.4, marketCapYi: 520, pe: 40, volatility: 0.034, pattern: "trend_up", growthTier: "high", description: "光无源器件与模块领先厂商，AI算力光互联核心供应商。" },
  { code: "600183", name: "生益科技", market: "沪主板", sector: "覆铜板", concept: "AI服务器PCB材料", listedDaysAgo: 20 * Y, isIndexMember: true, isNewIpo: false, basePrice: 26.4, marketCapYi: 560, pe: 28, volatility: 0.026, pattern: "trend_up", growthTier: "mid", description: "国内覆铜板龙头企业，高速材料受益AI服务器需求提升。" },
  { code: "002916", name: "深南电路", market: "深主板", sector: "PCB", concept: "AI服务器PCB", listedDaysAgo: 8 * Y, isIndexMember: true, isNewIpo: false, basePrice: 98.5, marketCapYi: 500, pe: 32, volatility: 0.03, pattern: "trend_up", growthTier: "mid", description: "国内高端PCB龙头企业，AI服务器与数通产品持续放量。" },
  { code: "002281", name: "光迅科技", market: "深主板", sector: "光模块", concept: "AI算力光器件", listedDaysAgo: 15 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.6, marketCapYi: 260, pe: 45, volatility: 0.032, pattern: "trend_up", growthTier: "mid", description: "国内领先的光电子器件供应商，光模块受益AI算力建设。" },
  { code: "601360", name: "三六零", market: "沪主板", sector: "网络安全+大模型", concept: "AI安全,大模型应用", listedDaysAgo: 8 * Y, isIndexMember: true, isNewIpo: false, basePrice: 14.2, marketCapYi: 780, pe: 0, volatility: 0.036, pattern: "volatile", growthTier: "mid", description: "国内网络安全龙头，纳米AI搜索等大模型应用持续推进。" },
  { code: "002261", name: "拓维信息", market: "深主板", sector: "AI算力生态", concept: "昇腾生态,教育AI", listedDaysAgo: 18 * Y, isIndexMember: true, isNewIpo: false, basePrice: 18.6, marketCapYi: 200, pe: 0, volatility: 0.042, pattern: "breakout", growthTier: "high", description: "华为昇腾计算生态核心合作伙伴，AI算力适配业务快速放量。" },
  { code: "300496", name: "中科创达", market: "创业板", sector: "智能操作系统", concept: "端侧AI,智能汽车", listedDaysAgo: 9 * Y, isIndexMember: true, isNewIpo: false, basePrice: 62.4, marketCapYi: 260, pe: 0, volatility: 0.038, pattern: "breakout", growthTier: "high", description: "全球智能操作系统领军企业，端侧大模型与智能汽车业务成长迅速。" },
  { code: "600728", name: "佳都科技", market: "沪主板", sector: "AI轨道交通", concept: "轨交AI,城市大脑", listedDaysAgo: 20 * Y, isIndexMember: true, isNewIpo: false, basePrice: 8.6, marketCapYi: 130, pe: 0, volatility: 0.045, pattern: "volatile", growthTier: "low", description: "智能轨道交通与城市大脑解决方案提供商。" },
  { code: "300609", name: "汇纳科技", market: "创业板", sector: "AI大数据零售", concept: "客流分析,零售AI", listedDaysAgo: 8 * Y, isIndexMember: true, isNewIpo: false, basePrice: 22.6, marketCapYi: 30, pe: 0, volatility: 0.05, pattern: "volatile", growthTier: "low", description: "商业大数据与AI客流分析服务提供商。" },
  { code: "688728", name: "格科微", market: "科创板", sector: "CIS芯片", concept: "图像传感器,消费电子", listedDaysAgo: 3 * Y, isIndexMember: true, isNewIpo: false, basePrice: 22.8, marketCapYi: 350, pe: 0, volatility: 0.03, pattern: "trend_up", growthTier: "mid", description: "国内CIS图像传感器龙头企业，高像素产品持续放量。" },
  { code: "688508", name: "芯朋微", market: "科创板", sector: "电源管理芯片", concept: "车规电源,国产替代", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.6, marketCapYi: 65, pe: 38, volatility: 0.032, pattern: "trend_up", growthTier: "mid", description: "国内电源管理芯片领先企业，车规级产品持续突破。" },
  { code: "688200", name: "华峰测控", market: "科创板", sector: "半导体测试设备", concept: "国产替代,测试机", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 168, marketCapYi: 165, pe: 48, volatility: 0.03, pattern: "trend_up", growthTier: "mid", description: "国产半导体测试机领军企业，模拟测试机全球市占率领先。" },
  { code: "300604", name: "长川科技", market: "创业板", sector: "半导体测试设备", concept: "国产替代,测试机", listedDaysAgo: 8 * Y, isIndexMember: true, isNewIpo: false, basePrice: 46.8, marketCapYi: 350, pe: 60, volatility: 0.034, pattern: "breakout", growthTier: "high", description: "国内半导体测试设备龙头企业，数字测试机快速放量。" },
  { code: "300567", name: "精测电子", market: "创业板", sector: "检测设备", concept: "半导体检测,面板检测", listedDaysAgo: 9 * Y, isIndexMember: true, isNewIpo: false, basePrice: 78.4, marketCapYi: 170, pe: 0, volatility: 0.036, pattern: "volatile", growthTier: "mid", description: "平板显示与半导体检测设备领先企业。" },
  { code: "300627", name: "华测导航", market: "创业板", sector: "北斗+AI导航", concept: "高精度定位,无人驾驶", listedDaysAgo: 10 * Y, isIndexMember: true, isNewIpo: false, basePrice: 42.6, marketCapYi: 210, pe: 32, volatility: 0.03, pattern: "trend_up", growthTier: "mid", description: "高精度导航定位领军企业，无人驾驶与低空经济打开空间。" },
  { code: "002236", name: "大华股份", market: "深主板", sector: "AI安防", concept: "视频物联,AI大模型", listedDaysAgo: 15 * Y, isIndexMember: true, isNewIpo: false, basePrice: 18.4, marketCapYi: 560, pe: 15, volatility: 0.024, pattern: "trend_up", growthTier: "mid", description: "全球领先的视频物联解决方案提供商，AI大模型赋能产品升级。" },
  { code: "002415", name: "海康威视", market: "深主板", sector: "AI安防", concept: "AI物联网,机器人", listedDaysAgo: 16 * Y, isIndexMember: true, isNewIpo: false, basePrice: 30.6, marketCapYi: 2900, pe: 18, volatility: 0.02, pattern: "trend_up", growthTier: "mid", description: "全球AIoT龙头企业，机器视觉与机器人业务快速成长。" },
  { code: "603486", name: "科沃斯", market: "沪主板", sector: "服务机器人", concept: "扫地机器人,AI算法", listedDaysAgo: 6 * Y, isIndexMember: true, isNewIpo: false, basePrice: 62.4, marketCapYi: 180, pe: 22, volatility: 0.032, pattern: "range", growthTier: "mid", description: "全球领先的家庭服务机器人企业。" },
  { code: "002747", name: "埃斯顿", market: "深主板", sector: "工业机器人", concept: "国产机器人,人形机器人", listedDaysAgo: 11 * Y, isIndexMember: true, isNewIpo: false, basePrice: 16.8, marketCapYi: 210, pe: 0, volatility: 0.04, pattern: "breakout", growthTier: "high", description: "国产工业机器人龙头企业，持续布局人形机器人核心部件。" },
  { code: "300124", name: "汇川技术", market: "创业板", sector: "工控+机器人", concept: "工业自动化,机器人核心部件", listedDaysAgo: 14 * Y, isIndexMember: true, isNewIpo: false, basePrice: 62.4, marketCapYi: 1650, pe: 35, volatility: 0.028, pattern: "trend_up", growthTier: "high", description: "国产工控与新能源汽车电驱龙头，机器人核心部件加速布局。" },
  { code: "688017", name: "绿的谐波", market: "科创板", sector: "机器人核心零部件", concept: "谐波减速器,人形机器人", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 68.4, marketCapYi: 170, pe: 60, volatility: 0.04, pattern: "breakout", growthTier: "high", description: "国产谐波减速器龙头企业，人形机器人关节部件核心供应商。" },
  { code: "688686", name: "奥普特", market: "科创板", sector: "机器视觉", concept: "工业视觉,3C检测", listedDaysAgo: 4 * Y, isIndexMember: true, isNewIpo: false, basePrice: 92.4, marketCapYi: 75, pe: 45, volatility: 0.036, pattern: "trend_up", growthTier: "mid", description: "国产工业机器视觉领先企业，3C与新能源检测需求稳健。" },
  { code: "688361", name: "中科飞测", market: "科创板", sector: "半导体检测设备", concept: "国产替代,量检测设备", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 78.6, marketCapYi: 210, pe: 0, volatility: 0.04, pattern: "breakout", growthTier: "high", description: "国产半导体质量控制设备领军企业，检测设备国产化加速。" },
  { code: "688469", name: "芯联集成", market: "科创板", sector: "功率半导体制造", concept: "碳化硅,车规芯片代工", listedDaysAgo: 2 * Y, isIndexMember: true, isNewIpo: false, basePrice: 12.6, marketCapYi: 480, pe: 0, volatility: 0.042, pattern: "breakout", growthTier: "high", description: "国内领先的特色工艺功率半导体晶圆代工企业，碳化硅产能持续爬坡。" },
  { code: "688775", name: "影石创新", market: "科创板", sector: "智能影像", concept: "全景相机,AI剪辑", listedDaysAgo: 1.5 * Y, isIndexMember: true, isNewIpo: false, basePrice: 128, marketCapYi: 520, pe: 38, volatility: 0.045, pattern: "breakout", growthTier: "high", description: "全球领先的智能影像设备企业，AI视频生成能力持续增强。" },

  // ================= 近期科创板新股（模拟近1-2年内新上市） =================
  { code: "688585", name: "西安奕材", market: "科创板", sector: "半导体材料", concept: "12英寸硅片,国产替代", listedDaysAgo: 220, isIndexMember: false, isNewIpo: true, basePrice: 16.8, marketCapYi: 320, pe: 0, volatility: 0.05, pattern: "breakout", growthTier: "high", description: "国内领先的12英寸硅片制造企业，产能持续释放。" },
  { code: "688691", name: "灿芯股份", market: "科创板", sector: "芯片设计服务", concept: "定制芯片,IP复用", listedDaysAgo: 250, isIndexMember: false, isNewIpo: true, basePrice: 28.4, marketCapYi: 85, pe: 0, volatility: 0.05, pattern: "breakout", growthTier: "high", description: "国内领先的芯片定制服务企业，先进制程订单快速增长。" },
  { code: "688584", name: "上海合晶", market: "科创板", sector: "半导体材料", concept: "外延片,车规半导体", listedDaysAgo: 200, isIndexMember: false, isNewIpo: true, basePrice: 22.6, marketCapYi: 95, pe: 0, volatility: 0.048, pattern: "trend_up", growthTier: "mid", description: "半导体外延片领先企业，车规级产品持续放量。" },
  { code: "688692", name: "达梦数据", market: "科创板", sector: "国产数据库", concept: "信创,数据库国产替代", listedDaysAgo: 260, isIndexMember: false, isNewIpo: true, basePrice: 98.6, marketCapYi: 260, pe: 0, volatility: 0.055, pattern: "breakout", growthTier: "high", description: "国产数据库管理系统领军企业，信创市场核心受益标的。" },
  { code: "688610", name: "埃科光电", market: "科创板", sector: "机器视觉", concept: "工业相机,AI质检", listedDaysAgo: 180, isIndexMember: false, isNewIpo: true, basePrice: 68.4, marketCapYi: 55, pe: 0, volatility: 0.05, pattern: "breakout", growthTier: "high", description: "工业机器视觉核心部件供应商，高端工业相机国产化提速。" },
  { code: "688543", name: "星宸科技", market: "科创板", sector: "AI视觉芯片", concept: "安防SoC,智能座舱", listedDaysAgo: 420, isIndexMember: false, isNewIpo: true, basePrice: 62.4, marketCapYi: 130, pe: 0, volatility: 0.045, pattern: "breakout", growthTier: "high", description: "智能视觉SoC芯片设计企业，安防与车载智能化持续拓展。" },
  { code: "688392", name: "骄成超声", market: "科创板", sector: "精密制造设备", concept: "超声波焊接,新能源", listedDaysAgo: 480, isIndexMember: false, isNewIpo: true, basePrice: 46.8, marketCapYi: 45, pe: 0, volatility: 0.05, pattern: "volatile", growthTier: "mid", description: "超声波焊接系统领先企业，新能源与半导体封装应用拓展。" },
  { code: "688590", name: "新致软件", market: "科创板", sector: "AI软件服务", concept: "金融IT,大模型应用", listedDaysAgo: 300, isIndexMember: false, isNewIpo: true, basePrice: 32.6, marketCapYi: 40, pe: 0, volatility: 0.05, pattern: "trend_up", growthTier: "mid", description: "金融行业软件服务商，积极布局大模型金融应用场景。" },
  { code: "688383", name: "唯捷创芯", market: "科创板", sector: "射频芯片", concept: "5G射频前端,国产替代", listedDaysAgo: 700, isIndexMember: false, isNewIpo: true, basePrice: 26.4, marketCapYi: 130, pe: 0, volatility: 0.045, pattern: "range", growthTier: "mid", description: "国产射频前端芯片领军企业，5G手机射频模组持续渗透。" },
  { code: "688517", name: "金冠电气", market: "科创板", sector: "电力设备+AI", concept: "智能电网,储能", listedDaysAgo: 900, isIndexMember: false, isNewIpo: false, basePrice: 18.6, marketCapYi: 35, pe: 0, volatility: 0.04, pattern: "volatile", growthTier: "low", description: "智能电网设备制造企业，储能与电网智能化产品线丰富。" },
  { code: "688049", name: "炬光科技", market: "科创板", sector: "激光器件", concept: "半导体激光,机器人感知", listedDaysAgo: 900, isIndexMember: false, isNewIpo: false, basePrice: 62.4, marketCapYi: 65, pe: 0, volatility: 0.045, pattern: "breakout", growthTier: "high", description: "半导体激光器领先企业，激光雷达与机器人感知应用拓展。" },
  { code: "688106", name: "金宏气体", market: "科创板", sector: "电子特气", concept: "半导体材料,国产替代", listedDaysAgo: 1400, isIndexMember: false, isNewIpo: false, basePrice: 22.4, marketCapYi: 150, pe: 28, volatility: 0.028, pattern: "trend_up", growthTier: "mid", description: "电子特种气体领军企业，半导体客户持续导入。" },
  { code: "688234", name: "天岳先进", market: "科创板", sector: "碳化硅材料", concept: "第三代半导体,新能源车", listedDaysAgo: 900, isIndexMember: false, isNewIpo: false, basePrice: 78.6, marketCapYi: 260, pe: 0, volatility: 0.048, pattern: "breakout", growthTier: "high", description: "全球领先的碳化硅衬底材料供应商，新能源车客户加速导入。" },
  { code: "688498", name: "源杰科技", market: "科创板", sector: "光芯片", concept: "AI算力,光模块芯片", listedDaysAgo: 800, isIndexMember: false, isNewIpo: false, basePrice: 128, marketCapYi: 105, pe: 0, volatility: 0.05, pattern: "breakout", growthTier: "high", description: "光通信激光器芯片领军企业，AI算力光模块国产化核心标的。" },
  { code: "688368", name: "晶丰明源", market: "科创板", sector: "模拟芯片", concept: "电源管理,国产替代", listedDaysAgo: 1300, isIndexMember: false, isNewIpo: false, basePrice: 68.4, marketCapYi: 85, pe: 0, volatility: 0.04, pattern: "range", growthTier: "mid", description: "国内领先的模拟与数模混合芯片设计企业。" },
  { code: "688330", name: "宏力达", market: "科创板", sector: "智能电力装备", concept: "配电网智能化", listedDaysAgo: 1000, isIndexMember: false, isNewIpo: false, basePrice: 62.4, marketCapYi: 65, pe: 22, volatility: 0.032, pattern: "trend_up", growthTier: "mid", description: "智能配电网装备制造企业，电网智能化改造持续推进。" },
  { code: "688766", name: "普冉股份", market: "科创板", sector: "存储芯片", concept: "EEPROM,NOR Flash", listedDaysAgo: 1000, isIndexMember: false, isNewIpo: false, basePrice: 58.4, marketCapYi: 60, pe: 0, volatility: 0.04, pattern: "volatile", growthTier: "mid", description: "非易失性存储器设计企业，消费与车规存储需求回暖。" },
  { code: "688981-2", name: "（预留）", market: "科创板", sector: "预留", concept: "", listedDaysAgo: 1, isIndexMember: false, isNewIpo: false, basePrice: 1, marketCapYi: 1, pe: 0, volatility: 0.01, pattern: "range", growthTier: "low", description: "预留占位，不参与展示。" },
];

// 移除占位项，保证真实展示数量
export const SEED_STOCKS_CLEAN: SeedStock[] = SEED_STOCKS.filter((s) => s.sector !== "预留");
